from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
from uuid import UUID

import asyncpg

from app.catalog import CatalogCompany
from app.time_utils import utc_now
from app.services.region_normalizer import RegionNormalizationInput, RegionNormalizationSummary, plan_region_normalization
from app.yfinance_client import FetchResult


REFRESH_LOCK_KEY = int.from_bytes(hashlib.sha256(b"ies_metadata_refresh_lock").digest()[:8], "big") & ((1 << 63) - 1)


CREATE_COMPANY_METADATA_SQL = """
CREATE TABLE IF NOT EXISTS public.ies_company_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL UNIQUE,
    company_name text NOT NULL,
    sector text NOT NULL DEFAULT '',
    industry text NOT NULL DEFAULT '',
    country text NOT NULL DEFAULT '',
    region text NOT NULL DEFAULT '',
    exchange text NOT NULL DEFAULT '',
    currency text NOT NULL DEFAULT '',
    revenue_ttm numeric,
    market_cap numeric,
    last_successful_refresh timestamptz,
    last_refresh_attempt timestamptz,
    refresh_status text NOT NULL DEFAULT 'never',
    last_error_message text,
    refresh_duration_ms integer,
    last_updated timestamptz NOT NULL DEFAULT now()
)
"""


CREATE_REFRESH_LOG_SQL = """
CREATE TABLE IF NOT EXISTS public.ies_refresh_log (
    run_id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NOT NULL,
    duration_ms integer NOT NULL DEFAULT 0,
    processed integer NOT NULL DEFAULT 0,
    inserted integer NOT NULL DEFAULT 0,
    updated integer NOT NULL DEFAULT 0,
    skipped integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    total_api_calls integer NOT NULL DEFAULT 0,
    validation_warnings integer NOT NULL DEFAULT 0,
    field_update_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL
)
"""


ALTER_COMPANY_METADATA_SQL = """
ALTER TABLE public.ies_company_metadata
    ADD COLUMN IF NOT EXISTS last_successful_refresh timestamptz,
    ADD COLUMN IF NOT EXISTS last_refresh_attempt timestamptz,
    ADD COLUMN IF NOT EXISTS refresh_status text NOT NULL DEFAULT 'never',
    ADD COLUMN IF NOT EXISTS last_error_message text,
    ADD COLUMN IF NOT EXISTS refresh_duration_ms integer
"""


ALTER_REFRESH_LOG_SQL = """
ALTER TABLE public.ies_refresh_log
    ADD COLUMN IF NOT EXISTS duration_ms integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS skipped integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_api_calls integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS validation_warnings integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS field_update_reasons jsonb NOT NULL DEFAULT '[]'::jsonb
"""


CREATE_INDEXES_SQL = """
CREATE INDEX IF NOT EXISTS ies_company_metadata_last_updated_idx
    ON public.ies_company_metadata (last_updated DESC);

CREATE INDEX IF NOT EXISTS ies_company_metadata_last_refresh_attempt_idx
    ON public.ies_company_metadata (last_refresh_attempt DESC);

CREATE INDEX IF NOT EXISTS ies_company_metadata_refresh_status_idx
    ON public.ies_company_metadata (refresh_status);

CREATE INDEX IF NOT EXISTS ies_refresh_log_started_at_idx
    ON public.ies_refresh_log (started_at DESC);

CREATE INDEX IF NOT EXISTS ies_refresh_log_status_idx
    ON public.ies_refresh_log (status);
"""


@dataclass(slots=True)
class CompanyMetadataRow:
    ticker: str
    company_name: str
    sector: str
    industry: str
    country: str
    region: str
    exchange: str
    currency: str
    revenue_ttm: Decimal | int | float | None
    market_cap: Decimal | int | float | None
    last_successful_refresh: datetime | None
    last_refresh_attempt: datetime | None
    refresh_status: str
    last_error_message: str | None
    refresh_duration_ms: int | None
    last_updated: datetime


@dataclass(slots=True)
class CompanyRefreshOutcome:
    inserted: bool
    updated_fields: list[str]
    skipped_fields: list[str]
    validation_warnings: list[str]
    field_update_reasons: list[str]

    @property
    def changed(self) -> bool:
        return self.inserted or bool(self.updated_fields)


@dataclass(slots=True)
class RefreshLockHandle:
    pool: asyncpg.Pool
    connection: asyncpg.Connection
    lock_key: int

    async def release(self) -> None:
        try:
            await self.connection.execute("SELECT pg_advisory_unlock($1)", self.lock_key)
        finally:
            await self.pool.release(self.connection)


@dataclass(slots=True)
class RefreshLogEntry:
    run_id: UUID
    started_at: datetime
    finished_at: datetime
    duration_ms: int
    processed: int
    inserted: int
    updated: int
    skipped: int
    failed: int
    total_api_calls: int
    validation_warnings: int
    field_update_reasons: list[str]
    status: str


FIELD_SPECS: list[tuple[str, str, str]] = [
    ("company_name", "company_name", "text"),
    ("sector", "sector", "text"),
    ("industry", "industry", "text"),
    ("country", "country", "text"),
    ("region", "region", "text"),
    ("exchange", "exchange", "text"),
    ("currency", "currency", "text"),
    ("revenue_ttm", "revenue_ttm", "numeric"),
    ("market_cap", "market_cap", "numeric"),
]


def _clean_text(value: Any) -> str | None:
    if isinstance(value, str):
        text = value.strip()
        return text or None
    return None


class DatabaseService:
    def __init__(self, database_url: str, *, min_size: int, max_size: int, command_timeout_seconds: float) -> None:
        self.database_url = database_url
        self.min_size = min_size
        self.max_size = max_size
        self.command_timeout_seconds = command_timeout_seconds
        self.pool: asyncpg.Pool | None = None

    async def open(self) -> None:
        if self.pool is None:
            self.pool = await asyncpg.create_pool(
                dsn=self.database_url,
                min_size=self.min_size,
                max_size=self.max_size,
                command_timeout=self.command_timeout_seconds,
            )

    async def close(self) -> None:
        if self.pool is not None:
            await self.pool.close()
            self.pool = None

    def _require_pool(self) -> asyncpg.Pool:
        if self.pool is None:
            raise RuntimeError("Database pool is not initialized")
        return self.pool

    async def ensure_schema(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(CREATE_COMPANY_METADATA_SQL)
            await connection.execute(ALTER_COMPANY_METADATA_SQL)
            await connection.execute(CREATE_REFRESH_LOG_SQL)
            await connection.execute(ALTER_REFRESH_LOG_SQL)
            await connection.execute(CREATE_INDEXES_SQL)

    async def ping(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute("SELECT 1")

    async def verify_tables_exist(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            row = await connection.fetchrow(
                """
                SELECT
                    to_regclass('public.ies_company_metadata') IS NOT NULL AS metadata_exists,
                    to_regclass('public.ies_refresh_log') IS NOT NULL AS refresh_log_exists
                """
            )
            if not row or not row["metadata_exists"] or not row["refresh_log_exists"]:
                raise RuntimeError("Required tables are missing")

    async def verify_upsert(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            transaction = connection.transaction()
            await transaction.start()
            try:
                now = utc_now()
                first = await self._apply_company_refresh_on_connection(
                    connection,
                    FetchResult(
                        ticker="__ies_validation__",
                        attempts=1,
                        catalog_company_name="Validation First",
                        started_at=now,
                        finished_at=now,
                        duration_ms=1,
                        company_name="Validation First",
                        sector=None,
                        industry=None,
                        country=None,
                        region=None,
                        exchange=None,
                        currency=None,
                        revenue_ttm=Decimal("1"),
                        market_cap=Decimal("1"),
                        last_updated=now,
                    ),
                    started_at=now,
                    finished_at=now,
                    duration_ms=1,
                )
                second = await self._apply_company_refresh_on_connection(
                    connection,
                    FetchResult(
                        ticker="__ies_validation__",
                        attempts=1,
                        catalog_company_name="Validation Second",
                        started_at=now,
                        finished_at=now,
                        duration_ms=1,
                        company_name="Validation Second",
                        sector=None,
                        industry=None,
                        country=None,
                        region=None,
                        exchange=None,
                        currency=None,
                        revenue_ttm=Decimal("2"),
                        market_cap=Decimal("2"),
                        last_updated=now,
                    ),
                    started_at=now,
                    finished_at=now,
                    duration_ms=1,
                )
                if not first or not second:
                    raise RuntimeError("UPSERT verification failed")
            finally:
                await transaction.rollback()

    async def acquire_refresh_lock(self) -> RefreshLockHandle | None:
        pool = self._require_pool()
        connection = await pool.acquire()
        try:
            locked = await connection.fetchval("SELECT pg_try_advisory_lock($1)", REFRESH_LOCK_KEY)
            if locked:
                return RefreshLockHandle(pool=pool, connection=connection, lock_key=REFRESH_LOCK_KEY)
            await pool.release(connection)
            return None
        except Exception:
            await pool.release(connection)
            raise

    async def insert_refresh_log(self, entry: RefreshLogEntry) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(
                """
                INSERT INTO public.ies_refresh_log (
                    run_id,
                    started_at,
                    finished_at,
                    duration_ms,
                    processed,
                    inserted,
                    updated,
                    skipped,
                    failed,
                    total_api_calls,
                    validation_warnings,
                    field_update_reasons,
                    status
                ) VALUES (
                    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::jsonb, $13
                )
                """,
                entry.run_id,
                entry.started_at,
                entry.finished_at,
                entry.duration_ms,
                entry.processed,
                entry.inserted,
                entry.updated,
                entry.skipped,
                entry.failed,
                entry.total_api_calls,
                entry.validation_warnings,
                json.dumps(entry.field_update_reasons),
                entry.status,
            )

    async def update_refresh_log(self, entry: RefreshLogEntry) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(
                """
                UPDATE public.ies_refresh_log
                SET finished_at = $2,
                    duration_ms = $3,
                    processed = $4,
                    inserted = $5,
                    updated = $6,
                    skipped = $7,
                    failed = $8,
                    total_api_calls = $9,
                    validation_warnings = $10,
                    field_update_reasons = $11::jsonb,
                    status = $12
                WHERE run_id = $1
                """,
                entry.run_id,
                entry.finished_at,
                entry.duration_ms,
                entry.processed,
                entry.inserted,
                entry.updated,
                entry.skipped,
                entry.failed,
                entry.total_api_calls,
                entry.validation_warnings,
                json.dumps(entry.field_update_reasons),
                entry.status,
            )

    async def apply_company_refresh(
        self,
        record: FetchResult,
        *,
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
    ) -> CompanyRefreshOutcome:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            transaction = connection.transaction()
            await transaction.start()
            try:
                outcome = await self._apply_company_refresh_on_connection(
                    connection,
                    record,
                    started_at=started_at,
                    finished_at=finished_at,
                    duration_ms=duration_ms,
                )
                await transaction.commit()
                return outcome
            except Exception:
                await transaction.rollback()
                raise

    async def record_company_failure(
        self,
        company: CatalogCompany,
        *,
        error_message: str,
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
    ) -> CompanyRefreshOutcome:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            transaction = connection.transaction()
            await transaction.start()
            try:
                outcome = await self._record_company_failure_on_connection(
                    connection,
                    company,
                    error_message=error_message,
                    started_at=started_at,
                    finished_at=finished_at,
                    duration_ms=duration_ms,
                )
                await transaction.commit()
                return outcome
            except Exception:
                await transaction.rollback()
                raise

    async def _fetch_company_row(self, connection: asyncpg.Connection, ticker: str) -> CompanyMetadataRow | None:
        row = await connection.fetchrow(
            """
            SELECT
                ticker,
                company_name,
                sector,
                industry,
                country,
                region,
                exchange,
                currency,
                revenue_ttm,
                market_cap,
                last_successful_refresh,
                last_refresh_attempt,
                refresh_status,
                last_error_message,
                refresh_duration_ms,
                last_updated
            FROM public.ies_company_metadata
            WHERE ticker = $1
            FOR UPDATE
            """,
            ticker,
        )
        if row is None:
            return None
        return CompanyMetadataRow(
            ticker=row["ticker"],
            company_name=row["company_name"],
            sector=row["sector"],
            industry=row["industry"],
            country=row["country"],
            region=row["region"],
            exchange=row["exchange"],
            currency=row["currency"],
            revenue_ttm=row["revenue_ttm"],
            market_cap=row["market_cap"],
            last_successful_refresh=row["last_successful_refresh"],
            last_refresh_attempt=row["last_refresh_attempt"],
            refresh_status=row["refresh_status"],
            last_error_message=row["last_error_message"],
            refresh_duration_ms=row["refresh_duration_ms"],
            last_updated=row["last_updated"],
        )

    async def _apply_company_refresh_on_connection(
        self,
        connection: asyncpg.Connection,
        record: FetchResult,
        *,
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
    ) -> CompanyRefreshOutcome:
        existing = await self._fetch_company_row(connection, record.ticker)
        merged, updated_fields, skipped_fields, validation_warnings, field_update_reasons = self._merge_company_values(
            existing,
            record,
        )

        company_name = merged["company_name"]
        if existing is None:
            await connection.execute(
                """
                INSERT INTO public.ies_company_metadata (
                    ticker,
                    company_name,
                    sector,
                    industry,
                    country,
                    region,
                    exchange,
                    currency,
                    revenue_ttm,
                    market_cap,
                    last_successful_refresh,
                    last_refresh_attempt,
                    refresh_status,
                    last_error_message,
                    refresh_duration_ms,
                    last_updated
                ) VALUES (
                    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
                )
                """,
                record.ticker,
                company_name,
                merged["sector"],
                merged["industry"],
                merged["country"],
                merged["region"],
                merged["exchange"],
                merged["currency"],
                merged["revenue_ttm"],
                merged["market_cap"],
                finished_at,
                started_at,
                "success" if updated_fields else "unchanged",
                None,
                duration_ms,
                finished_at if updated_fields else started_at,
            )
            return CompanyRefreshOutcome(
                inserted=True,
                updated_fields=[field for field in updated_fields if field in merged],
                skipped_fields=skipped_fields,
                validation_warnings=validation_warnings,
                field_update_reasons=field_update_reasons,
            )

        update_columns: list[str] = []
        update_values: list[Any] = []
        for column, value in merged.items():
            if column == "company_name":
                if value != existing.company_name:
                    update_columns.append("company_name")
                    update_values.append(value)
            elif column == "sector":
                if value != existing.sector:
                    update_columns.append("sector")
                    update_values.append(value)
            elif column == "industry":
                if value != existing.industry:
                    update_columns.append("industry")
                    update_values.append(value)
            elif column == "country":
                if value != existing.country:
                    update_columns.append("country")
                    update_values.append(value)
            elif column == "region":
                if value != existing.region:
                    update_columns.append("region")
                    update_values.append(value)
            elif column == "exchange":
                if value != existing.exchange:
                    update_columns.append("exchange")
                    update_values.append(value)
            elif column == "currency":
                if value != existing.currency:
                    update_columns.append("currency")
                    update_values.append(value)
            elif column == "revenue_ttm":
                if value != existing.revenue_ttm:
                    update_columns.append("revenue_ttm")
                    update_values.append(value)
            elif column == "market_cap":
                if value != existing.market_cap:
                    update_columns.append("market_cap")
                    update_values.append(value)

        refresh_status = "success" if update_columns else "unchanged"
        if update_columns:
            update_columns.extend(
                [
                    "last_successful_refresh",
                    "last_refresh_attempt",
                    "refresh_status",
                    "refresh_duration_ms",
                    "last_updated",
                ]
            )
            update_values.extend([finished_at, started_at, refresh_status, duration_ms, finished_at])
        else:
            update_columns.extend(
                [
                    "last_successful_refresh",
                    "last_refresh_attempt",
                    "refresh_status",
                    "refresh_duration_ms",
                ]
            )
            update_values.extend([finished_at, started_at, refresh_status, duration_ms])

        await self._execute_dynamic_update(connection, record.ticker, update_columns, update_values)
        return CompanyRefreshOutcome(
            inserted=False,
            updated_fields=updated_fields,
            skipped_fields=skipped_fields,
            validation_warnings=validation_warnings,
            field_update_reasons=field_update_reasons,
        )

    async def _record_company_failure_on_connection(
        self,
        connection: asyncpg.Connection,
        company: CatalogCompany,
        *,
        error_message: str,
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
    ) -> CompanyRefreshOutcome:
        existing = await self._fetch_company_row(connection, company.ticker)
        fallback_company_name = company.company_name or company.ticker

        if existing is None:
            await connection.execute(
                """
                INSERT INTO public.ies_company_metadata (
                    ticker,
                    company_name,
                    sector,
                    industry,
                    country,
                    region,
                    exchange,
                    currency,
                    revenue_ttm,
                    market_cap,
                    last_successful_refresh,
                    last_refresh_attempt,
                    refresh_status,
                    last_error_message,
                    refresh_duration_ms,
                    last_updated
                ) VALUES (
                    $1, $2, '', '', '', '', '', '', NULL, NULL, NULL, $3, 'failed', $4, $5, $6
                )
                """,
                company.ticker,
                fallback_company_name,
                started_at,
                error_message,
                duration_ms,
                finished_at,
            )
            return CompanyRefreshOutcome(
                inserted=True,
                updated_fields=[],
                skipped_fields=[],
                validation_warnings=[],
                field_update_reasons=[f"{company.ticker}:failed:{error_message}"],
            )

        await connection.execute(
            """
            UPDATE public.ies_company_metadata
            SET last_refresh_attempt = $2,
                refresh_status = 'failed',
                last_error_message = $3,
                refresh_duration_ms = $4,
                last_updated = $5
            WHERE ticker = $1
            """,
            company.ticker,
            started_at,
            error_message,
            duration_ms,
            finished_at,
        )
        return CompanyRefreshOutcome(
            inserted=False,
            updated_fields=[],
            skipped_fields=[],
            validation_warnings=[],
            field_update_reasons=[f"{company.ticker}:failed:{error_message}"],
        )

    async def normalize_regions(self) -> RegionNormalizationSummary:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            transaction = connection.transaction()
            await transaction.start()
            try:
                rows = await connection.fetch(
                    """
                    SELECT ticker, country, region
                    FROM public.ies_company_metadata
                    WHERE country IS NOT NULL
                      AND btrim(country) <> ''
                    ORDER BY ticker
                    """
                )
                plan = plan_region_normalization(
                    RegionNormalizationInput(
                        ticker=row["ticker"],
                        country=row["country"],
                        current_region=row["region"],
                    )
                    for row in rows
                )
                if plan.updates:
                    await self._bulk_update_regions(connection, plan.updates)
                await transaction.commit()
                return plan.summary
            except Exception:
                await transaction.rollback()
                raise

    async def _execute_dynamic_update(
        self,
        connection: asyncpg.Connection,
        ticker: str,
        columns: list[str],
        values: list[Any],
    ) -> None:
        assignments = ", ".join(f"{column} = ${index}" for index, column in enumerate(columns, start=2))
        sql = f"UPDATE public.ies_company_metadata SET {assignments} WHERE ticker = $1"
        await connection.execute(sql, ticker, *values)

    async def _bulk_update_regions(
        self,
        connection: asyncpg.Connection,
        updates: list["RegionNormalizationUpdate"],
        *,
        chunk_size: int = 1000,
    ) -> None:
        for index in range(0, len(updates), chunk_size):
            chunk = updates[index : index + chunk_size]
            values: list[Any] = []
            placeholders: list[str] = []
            for chunk_index, update in enumerate(chunk, start=1):
                placeholder_offset = (chunk_index - 1) * 3
                placeholders.append(
                    f"(${placeholder_offset + 1}, ${placeholder_offset + 2}, ${placeholder_offset + 3})"
                )
                values.extend([update.ticker, update.expected_region, utc_now()])

            sql = f"""
            UPDATE public.ies_company_metadata AS company
            SET region = data.region,
                last_updated = data.last_updated
            FROM (VALUES {', '.join(placeholders)}) AS data(ticker, region, last_updated)
            WHERE company.ticker = data.ticker
              AND company.region IS DISTINCT FROM data.region
            """
            await connection.execute(sql, *values)

    def _merge_company_values(
        self,
        existing: CompanyMetadataRow | None,
        record: FetchResult,
    ) -> tuple[dict[str, Any], list[str], list[str], list[str], list[str]]:
        merged: dict[str, Any] = {}
        updated_fields: list[str] = []
        skipped_fields: list[str] = []
        validation_warnings: list[str] = []
        field_update_reasons: list[str] = []

        def current_value(column: str) -> Any:
            if existing is None:
                return None
            return getattr(existing, column)

        def merge_text(column: str, fetched_value: Any, *, fallback_value: Any | None = None) -> None:
            existing_value = current_value(column)
            normalized_fetched = _clean_text(fetched_value)
            if normalized_fetched is None:
                if existing_value is None and fallback_value is not None:
                    normalized_fetched = _clean_text(fallback_value)
                else:
                    merged[column] = existing_value if existing_value is not None else ""
                    skipped_fields.append(column)
                    return
            if existing_value is None:
                merged[column] = normalized_fetched
                updated_fields.append(column)
                field_update_reasons.append(f"{record.ticker}.{column}:field_empty")
                return
            if str(existing_value).strip() != normalized_fetched:
                merged[column] = normalized_fetched
                updated_fields.append(column)
                field_update_reasons.append(f"{record.ticker}.{column}:data_changed")
                return
            merged[column] = existing_value if existing_value is not None else ""
            skipped_fields.append(column)

        def normalize_numeric(value: Any) -> Decimal | None:
            if value is None or isinstance(value, bool):
                return None
            if isinstance(value, Decimal):
                return value
            if isinstance(value, int):
                return Decimal(value)
            if isinstance(value, float):
                return Decimal(str(value))
            try:
                return Decimal(str(value))
            except Exception:
                return None

        def merge_numeric(column: str, fetched_value: Any) -> None:
            existing_value = current_value(column)
            normalized_fetched = normalize_numeric(fetched_value)
            if normalized_fetched is None:
                merged[column] = existing_value
                skipped_fields.append(column)
                return
            if normalized_fetched < 0:
                validation_warnings.append(f"{record.ticker}.{column}:negative_value_skipped")
                merged[column] = existing_value
                skipped_fields.append(column)
                return
            if column == "market_cap" and normalized_fetched <= 0:
                validation_warnings.append(f"{record.ticker}.{column}:non_positive_value_skipped")
                merged[column] = existing_value
                skipped_fields.append(column)
                return
            if existing_value is None:
                merged[column] = normalized_fetched
                updated_fields.append(column)
                field_update_reasons.append(f"{record.ticker}.{column}:field_empty")
                return
            normalized_existing = normalize_numeric(existing_value)
            if normalized_existing is None:
                merged[column] = normalized_fetched
                updated_fields.append(column)
                field_update_reasons.append(f"{record.ticker}.{column}:field_empty")
                return
            if normalized_existing != normalized_fetched:
                merged[column] = normalized_fetched
                updated_fields.append(column)
                if normalized_fetched > normalized_existing:
                    field_update_reasons.append(f"{record.ticker}.{column}:newer_information")
                else:
                    field_update_reasons.append(f"{record.ticker}.{column}:data_changed")
                return
            merged[column] = normalized_existing
            skipped_fields.append(column)

        merge_text("company_name", record.company_name, fallback_value=record.catalog_company_name or record.ticker)
        merge_text("sector", record.sector)
        merge_text("industry", record.industry)
        merge_text("country", record.country)
        merge_text("region", record.region)
        merge_text("exchange", record.exchange)
        merge_text("currency", record.currency)
        merge_numeric("revenue_ttm", record.revenue_ttm)
        merge_numeric("market_cap", record.market_cap)

        if existing is not None and not updated_fields:
            merged["company_name"] = existing.company_name

        return merged, updated_fields, skipped_fields, validation_warnings, field_update_reasons
