from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from uuid import UUID

import asyncpg

from app.yfinance_client import FetchResult


CREATE_COMPANY_METADATA_SQL = """
CREATE TABLE IF NOT EXISTS public.ies_company_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL UNIQUE,
    company_name text NOT NULL,
    sector text NOT NULL DEFAULT '',
    industry text NOT NULL DEFAULT '',
    country text NOT NULL DEFAULT '',
    region text NOT NULL DEFAULT '',
    exchange text NOT NULL DEFAULT '',
    currency text NOT NULL DEFAULT '',
    revenue_ttm numeric,
    market_cap numeric,
    last_updated timestamptz NOT NULL DEFAULT now()
)
"""


CREATE_REFRESH_LOG_SQL = """
CREATE TABLE IF NOT EXISTS public.ies_refresh_log (
    run_id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NOT NULL,
    processed integer NOT NULL DEFAULT 0,
    inserted integer NOT NULL DEFAULT 0,
    updated integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    duration_seconds numeric(12,3) NOT NULL DEFAULT 0,
    status text NOT NULL
)
"""


CREATE_INDEXES_SQL = """
CREATE INDEX IF NOT EXISTS ies_company_metadata_last_updated_idx
    ON public.ies_company_metadata (last_updated DESC);

CREATE INDEX IF NOT EXISTS ies_refresh_log_started_at_idx
    ON public.ies_refresh_log (started_at DESC);

CREATE INDEX IF NOT EXISTS ies_refresh_log_status_idx
    ON public.ies_refresh_log (status);
"""


UPSERT_METADATA_SQL = """
INSERT INTO public.ies_company_metadata (
    ticker,
    company_name,
    sector,
    industry,
    country,
    region,
    exchange,
    currency,
    revenue_ttm,
    market_cap,
    last_updated
) VALUES (
    $1,
    COALESCE($2, $1),
    COALESCE($3, ''),
    COALESCE($4, ''),
    COALESCE($5, ''),
    COALESCE($6, ''),
    COALESCE($7, ''),
    COALESCE($8, ''),
    $9,
    $10,
    $11
)
ON CONFLICT (ticker) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    sector = EXCLUDED.sector,
    industry = EXCLUDED.industry,
    country = EXCLUDED.country,
    region = EXCLUDED.region,
    exchange = EXCLUDED.exchange,
    currency = EXCLUDED.currency,
    revenue_ttm = EXCLUDED.revenue_ttm,
    market_cap = EXCLUDED.market_cap,
    last_updated = EXCLUDED.last_updated
RETURNING (xmax = 0) AS inserted
"""


INSERT_REFRESH_LOG_SQL = """
INSERT INTO public.ies_refresh_log (
    run_id,
    started_at,
    finished_at,
    processed,
    inserted,
    updated,
    failed,
    duration_seconds,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
"""


UPDATE_REFRESH_LOG_SQL = """
UPDATE public.ies_refresh_log
SET finished_at = $2,
    processed = $3,
    inserted = $4,
    updated = $5,
    failed = $6,
    duration_seconds = $7,
    status = $8
WHERE run_id = $1
"""


@dataclass(slots=True)
class RefreshLogEntry:
    run_id: UUID
    started_at: datetime
    finished_at: datetime
    processed: int
    inserted: int
    updated: int
    failed: int
    duration_seconds: Decimal
    status: str


class DatabaseService:
    def __init__(self, database_url: str, *, min_size: int, max_size: int, command_timeout_seconds: float) -> None:
        self.database_url = database_url
        self.min_size = min_size
        self.max_size = max_size
        self.command_timeout_seconds = command_timeout_seconds
        self.pool: asyncpg.Pool | None = None

    async def open(self) -> None:
        if self.pool is None:
            self.pool = await asyncpg.create_pool(
                dsn=self.database_url,
                min_size=self.min_size,
                max_size=self.max_size,
                command_timeout=self.command_timeout_seconds,
            )

    async def close(self) -> None:
        if self.pool is not None:
            await self.pool.close()
            self.pool = None

    def _require_pool(self) -> asyncpg.Pool:
        if self.pool is None:
            raise RuntimeError("Database pool is not initialized")
        return self.pool

    async def ensure_schema(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(CREATE_COMPANY_METADATA_SQL)
            await connection.execute(CREATE_REFRESH_LOG_SQL)
            await connection.execute(CREATE_INDEXES_SQL)

    async def ping(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute("SELECT 1")

    async def verify_tables_exist(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            row = await connection.fetchrow(
                """
                SELECT
                    to_regclass('public.ies_company_metadata') IS NOT NULL AS metadata_exists,
                    to_regclass('public.ies_refresh_log') IS NOT NULL AS refresh_log_exists
                """
            )
            if not row or not row["metadata_exists"] or not row["refresh_log_exists"]:
                raise RuntimeError("Required tables are missing")

    async def verify_upsert(self) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            transaction = connection.transaction()
            await transaction.start()
            try:
                first = await connection.fetchrow(
                    UPSERT_METADATA_SQL,
                    "__ies_validation__",
                    "Validation First",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    1,
                    1,
                    datetime.now(timezone.utc),
                )
                second = await connection.fetchrow(
                    UPSERT_METADATA_SQL,
                    "__ies_validation__",
                    "Validation Second",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    2,
                    2,
                    datetime.now(timezone.utc),
                )
                if not first or not second:
                    raise RuntimeError("UPSERT verification failed")
            finally:
                await transaction.rollback()

    async def upsert_company(self, record: FetchResult) -> bool:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            row = await connection.fetchrow(
                UPSERT_METADATA_SQL,
                record.ticker,
                record.company_name,
                record.sector,
                record.industry,
                record.country,
                record.region,
                record.exchange,
                record.currency,
                record.revenue_ttm,
                record.market_cap,
                record.last_updated,
            )
            return bool(row["inserted"])

    async def insert_refresh_log(self, entry: RefreshLogEntry) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(
                INSERT_REFRESH_LOG_SQL,
                entry.run_id,
                entry.started_at,
                entry.finished_at,
                entry.processed,
                entry.inserted,
                entry.updated,
                entry.failed,
                entry.duration_seconds,
                entry.status,
            )

    async def update_refresh_log(self, entry: RefreshLogEntry) -> None:
        pool = self._require_pool()
        async with pool.acquire() as connection:
            await connection.execute(
                UPDATE_REFRESH_LOG_SQL,
                entry.run_id,
                entry.finished_at,
                entry.processed,
                entry.inserted,
                entry.updated,
                entry.failed,
                entry.duration_seconds,
                entry.status,
            )
